name: Build ARM64 Red Eclipse

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable ARM64 architecture
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update

      - name: Install Dependencies
        run: |
          sudo apt-get install -y \
            unzip \
            build-essential \
            make \
            pkg-config \
            cmake \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libgl1-mesa-dev:arm64 \
            libsdl2-dev:arm64 \
            libsdl2-image-dev:arm64 \
            libsdl2-mixer-dev:arm64

      - name: Extract Source
        run: |
          unzip base-2.0.0.zip
          mv base-2.0.0 redeclipse

      - name: Build
        run: |
          cd redeclipse/src

          make \
            CC=aarch64-linux-gnu-gcc \
            CXX=aarch64-linux-gnu-g++ \
            AR=aarch64-linux-gnu-ar \
            RANLIB=aarch64-linux-gnu-ranlib \
            PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig \
            CLIENT_INCLUDES="-I/usr/include/SDL2 -D_REENTRANT -DSDL_DISABLE_IMMINTRIN_H"

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: redeclipse-arm64
          path: redeclipse/src/redeclipse*
