- name: Install Dependencies
  run: |
    sudo apt update
    sudo apt install -y \
      unzip \
      build-essential \
      make \
      pkg-config \
      gcc-aarch64-linux-gnu \
      g++-aarch64-linux-gnu \
      libsdl2-dev \
      libsdl2-image-dev \
      libsdl2-mixer-dev \
      libgl1-mesa-dev

- name: Build
  run: |
    cd redeclipse/src

    export CC=aarch64-linux-gnu-gcc
    export CXX=aarch64-linux-gnu-g++

    make \
      CC=$CC \
      CXX=$CXX \
      AR=aarch64-linux-gnu-ar \
      RANLIB=aarch64-linux-gnu-ranlib \
      CLIENT_INCLUDES="$(pkg-config --cflags sdl2)"
